/**
 * Single source of truth for the `k-*` design-system class tokens emitted by
 * the block renderers. These map 1:1 to selectors in `style.css`.
 *
 * Grid classes (`k-grid-2/-3/-4`) are intentionally NOT listed here — they are
 * generated dynamically by `gridClass()` in `utils.ts`, which clamps the column
 * count to the [2,4] range that actually has CSS rules.
 */
export const K = {
  eyebrow: 'k-eyebrow',
  eyebrowDark: 'k-eyebrow-dark',
  card: 'k-card',
  dark: 'k-dark',
  btn: 'k-btn',
  btnGhost: 'k-btn-ghost',
  author: 'k-author',
  quote: 'k-quote',
  quoteCard: 'k-quote-card',
  num: 'k-num',
  cover: 'k-cover',
  coverFullBleed: 'k-cover--full-bleed',
  coverMain: 'k-cover-main',
  coverCopy: 'k-cover-copy',
  coverTitle: 'k-cover-title',
  coverPeople: 'k-cover-people',
  personCard: 'k-person-card',
  personAvatar: 'k-person-avatar',
  personInitials: 'k-person-initials',
  personBody: 'k-person-body',
  personName: 'k-person-name',
  personTitle: 'k-person-title',
  heroBig: 'k-hero-big',
  heroSub: 'k-hero-sub',
  ctaFrame: 'k-cta-frame',
  ctaTitle: 'k-cta-title',
  ctaSub: 'k-cta-sub',
  ctaActions: 'k-cta-actions',
  ctaCaption: 'k-cta-caption',
  sectionNum: 'k-section-num',
  sectionSub: 'k-section-sub',
  sectionSubWide: 'k-section-sub--wide',
  sectionSubNarrow: 'k-section-sub--narrow',
  content: 'k-content',
  contentTight: 'k-content-tight',
  contentFull: 'k-content--full',
  contentHeader: 'k-content-header',
  contentHeaderSplit: 'k-content-header--split',
  contentHeaderCenter: 'k-content-header--center',
  contentMain: 'k-content-main',
  contentMainCenter: 'k-content-main--center',
  contentMainStart: 'k-content-main--start',
  contentMainStretch: 'k-content-main--stretch',
  cardStack: 'k-card-stack',
  cardStackGrid: 'k-card-stack--grid',
  cardStackColumn: 'k-card-stack--column',
  hero: 'k-hero',
  heroMain: 'k-hero-main',
  heroTitle: 'k-hero-title',
  heroBody: 'k-hero-body',
  heroCaption: 'k-hero-caption',
  split: 'k-split',
  divider: 'k-divider',
  stat: 'k-stat',
  statCard: 'k-stat-card',
  statGrid: 'k-stat-grid',
  statVal: 'val',
  statLabel: 'lbl',
  table: 'k-table',
  timeline: 'k-timeline',
  timelineHorizontal: 'k-timeline--horizontal',
  timelineVertical: 'k-timeline--vertical',
  timelineStep: 'k-tl-step',
  timelineDot: 'k-tl-dot',
  timelineLabel: 'k-tl-label',
  timelineDesc: 'k-tl-desc',
  timelineBand: 'k-tl-band',
  agenda: 'k-agenda',
  agendaItem: 'k-ag-item',
  agendaItemActive: 'k-ag-item--active',
  agendaItemDim: 'k-ag-item--dim',
  agendaNum: 'k-ag-num',
  agendaLabel: 'k-ag-label',
  agendaDesc: 'k-ag-desc',
  caption: 'k-caption',
  pill: 'k-pill',
  defItem: 'k-def-item',
  defIndex: 'k-def-index',
  defText: 'k-def-text',
  defFooter: 'k-def-footer',
  defRef: 'k-def-ref',
} as const;
