/**
 * Single source of truth for the `k-*` design-system class tokens emitted by
 * the block renderers. These map 1:1 to selectors in `style.css`.
 *
 * Grid classes (`k-grid-2/-3/-4`) are intentionally NOT listed here — they are
 * generated dynamically by `gridClass()` in `utils.ts`, which clamps the column
 * count to the [2,4] range that actually has CSS rules.
 */
export const K = {
  eyebrow: 'k-eyebrow',
  eyebrowDark: 'k-eyebrow-dark',
  card: 'k-card',
  dark: 'k-dark',
  btn: 'k-btn',
  btnGhost: 'k-btn-ghost',
  author: 'k-author',
  quote: 'k-quote',
  num: 'k-num',
  cover: 'k-cover',
  coverPeople: 'k-cover-people',
  personCard: 'k-person-card',
  personAvatar: 'k-person-avatar',
  personInitials: 'k-person-initials',
  personBody: 'k-person-body',
  personName: 'k-person-name',
  personTitle: 'k-person-title',
  heroBig: 'k-hero-big',
  heroSub: 'k-hero-sub',
  ctaTitle: 'k-cta-title',
  ctaSub: 'k-cta-sub',
  sectionNum: 'k-section-num',
  split: 'k-split',
  divider: 'k-divider',
  stat: 'k-stat',
  table: 'k-table',
  timeline: 'k-timeline',
  timelineHorizontal: 'k-timeline--horizontal',
  timelineVertical: 'k-timeline--vertical',
  timelineStep: 'k-tl-step',
  timelineDot: 'k-tl-dot',
  timelineLabel: 'k-tl-label',
  timelineDesc: 'k-tl-desc',
  timelineBand: 'k-tl-band',
  agenda: 'k-agenda',
  agendaItem: 'k-ag-item',
  agendaItemActive: 'k-ag-item--active',
  agendaItemDim: 'k-ag-item--dim',
  agendaNum: 'k-ag-num',
  agendaLabel: 'k-ag-label',
  agendaDesc: 'k-ag-desc',
  caption: 'k-caption',
  pill: 'k-pill',
  defItem: 'k-def-item',
  defIndex: 'k-def-index',
  defText: 'k-def-text',
  defFooter: 'k-def-footer',
  defRef: 'k-def-ref',
} as const;
